# 数据库配置
host: localhost
port: 3306
database: nations
username: root
password: root

# 连接池配置
pool:
  # 最大连接数
  maximum-pool-size: 10
  # 最小空闲连接数
  minimum-idle: 5
  # 连接最大生命周期（毫秒）
  maximum-lifetime: 1800000
  # 连接超时时间（毫秒）
  connection-timeout: 5000
  # 空闲超时时间（毫秒）
  idle-timeout: 600000

# 数据库表前缀（可选）
table-prefix: nc_ 