name: NationsCore
version: '${project.version}'
main: com.nations.core.NationsCore
api-version: '1.20'
depend: [Vault, Citizens]
softdepend: [PlaceholderAPI]
commands:
  nation:
    description: 国家系统主命令
    usage: /nation help
  nadmin:
    description: 国家系统管理命令
    usage: /nadmin help