# NationsCore 配置文件

# 数据库设置
database:
  host: localhost
  port: 3306
  database: nations
  username: root
  password: root
  table-prefix: nc_
  pool:
    # 每个子服只需要少量连接
    maximum-pool-size: 5
    minimum-idle: 2
    connection-timeout: 5000
    idle-timeout: 300000

# 国家系统设置
nations:
  # 创建国家的费用
  creation:
    money: 10000.0  # 金钱消耗
    items:  # 物品消耗
      DIAMOND: 10  # 钻石 10个
      EMERALD: 5   # 绿宝石 5个
      NETHERITE_INGOT: 1  # 下界合金锭 1个
  
  # 国家名称设置
  min-name-length: 2
  max-name-length: 16
  name-regex: "^[\u4e00-\u9fa5a-zA-Z0-9_]+$"
  
  # 国家等级设置
  levels:
    1:
      name: "新兴国家"
      max-members: 10
      max-territory: 30  # 30x30
      upgrade-cost:
        money: 0  # 初始等级无需费用
        items: {}
      max-buildings: 3  # 1级国家最多3个建筑
    2:
      name: "发展中国家"
      max-members: 20
      max-territory: 50  # 50x50
      upgrade-cost:
        money: 50000
        items:
          DIAMOND: 20
          EMERALD: 10
          NETHERITE_INGOT: 2
      max-buildings: 5
    3:
      name: "地区强国"
      max-members: 30
      max-territory: 70  # 70x70
      upgrade-cost:
        money: 100000
        items:
          DIAMOND: 40
          EMERALD: 20
          NETHERITE_INGOT: 4
      max-buildings: 8
    4:
      name: "世界强国"
      max-members: 50
      max-territory: 100  # 100x100
      upgrade-cost:
        money: 200000
        items:
          DIAMOND: 80
          EMERALD: 40
          NETHERITE_INGOT: 8
      max-buildings: 12

# NPC技能配置
npc:
  skills:
    # 农民技能
    EFFICIENT_FARMING:
      unlock_cost: 1000.0
      description: "提高作物生长速度"
      max_level: 10
      effectiveness_per_level: 0.1  # 每级增加10%效果
    
    HARVEST_MASTER:
      unlock_cost: 1500.0
      description: "增加作物产量"
      max_level: 10
      effectiveness_per_level: 0.08  # 每级增加8%产量
    
    CROP_EXPERT:
      unlock_cost: 2000.0
      description: "提高稀有作物产出概率"
      max_level: 10
      effectiveness_per_level: 0.05  # 每级增加5%概率
    
    # 守卫技能
    COMBAT_MASTERY:
      unlock_cost: 2000.0
      description: "提高攻击力"
      max_level: 10
      effectiveness_per_level: 0.1  # 每级增加10%攻击力
    
    DEFENSIVE_STANCE:
      unlock_cost: 1500.0
      description: "提高防御力"
      max_level: 10
      effectiveness_per_level: 0.12  # 每级增加12%防御力
    
    PATROL_EFFICIENCY:
      unlock_cost: 1000.0
      description: "提高巡逻范围和效率"
      max_level: 10
      effectiveness_per_level: 0.15  # 每级增加15%范围

    # 商人技能
    BARGAINING:
      unlock_cost: 1500.0
      description: "提高交易获得的金币"
      max_level: 10
      effectiveness_per_level: 0.1  # 每级增加10%金币
    
    MARKET_INSIGHT:
      unlock_cost: 2000.0
      description: "解锁更多交易选项"
      max_level: 10
      effectiveness_per_level: 0.1  # 每级增加一个交易选项
    
    TRADE_NETWORK:
      unlock_cost: 1800.0
      description: "提高交易频率"
      max_level: 10
      effectiveness_per_level: 0.08  # 每级增加8%频率

    # 管理者技能
    LEADERSHIP:
      unlock_cost: 2000.0
      description: "提高其他NPC的工作效率"
      max_level: 10
      effectiveness_per_level: 0.1  # 每级增加10%效率
    
    RESOURCE_MANAGEMENT:
      unlock_cost: 1500.0
      description: "降低NPC维护成本"
      max_level: 10
      effectiveness_per_level: 0.08  # 每级降低8%成本
    
    CRISIS_HANDLING:
      unlock_cost: 1800.0
      description: "提高建筑防御和修复速度"
      max_level: 10
      effectiveness_per_level: 0.12  # 每级增加12%速度

# GUI设置
gui:
  # 边框颜色
  border-color: GRAY_STAINED_GLASS_PANE
  # 是否显示物品提示
  show-tooltips: true 

# 权限设置
permissions:
  ranks:
    OWNER:
      - nation.building  # 国家建筑管理权限
      # ... 其他权限
    ADMIN:
      - nation.building
      # ... 其他权限
    MEMBER:
      # 普通成员没有建筑管理权限
      # ... 其他权限