# NationsCore 配置文件

# 数据库设置
database:
  host: localhost
  port: 3306
  database: nations
  username: root
  password: root
  table-prefix: nc_
  pool:
    # 每个子服只需要少量连接
    maximum-pool-size: 5
    minimum-idle: 2
    connection-timeout: 5000
    idle-timeout: 300000

# 国家系统设置
nations:
  # 创建国家的费用
  creation:
    money: 10000.0  # 金钱消耗
    items:  # 物品消耗
      DIAMOND: 10  # 钻石 10个
      EMERALD: 5   # 绿宝石 5个
      NETHERITE_INGOT: 1  # 下界合金锭 1个
  
  # 国家名称设置
  min-name-length: 2
  max-name-length: 16
  name-regex: "^[\u4e00-\u9fa5a-zA-Z0-9_]+$"
  
  # 国家等级设置
  levels:
    1:
      name: "新兴国家"
      max-members: 10
      max-territory: 30  # 30x30
      upgrade-cost:
        money: 0  # 初始等级无需费用
        items: {}
    2:
      name: "发展中国家"
      max-members: 20
      max-territory: 50  # 50x50
      upgrade-cost:
        money: 50000
        items:
          DIAMOND: 20
          EMERALD: 10
          NETHERITE_INGOT: 2
    3:
      name: "地区强国"
      max-members: 30
      max-territory: 70  # 70x70
      upgrade-cost:
        money: 100000
        items:
          DIAMOND: 40
          EMERALD: 20
          NETHERITE_INGOT: 4
    4:
      name: "世界强国"
      max-members: 50
      max-territory: 100  # 100x100
      upgrade-cost:
        money: 200000
        items:
          DIAMOND: 80
          EMERALD: 40
          NETHERITE_INGOT: 8

# GUI设置
gui:
  # 边框颜色
  border-color: GRAY_STAINED_GLASS_PANE
  # 是否显示物品提示
  show-tooltips: true 